v5.1

diff --git a/packaging/arch/PKGBUILD b/packaging/arch/PKGBUILD
--- a/packaging/arch/PKGBUILD
+++ b/packaging/arch/PKGBUILD
@@ -1,5 +1,5 @@
 pkgname=tuxpulse
-pkgver=2.0
+pkgver=5.1
 pkgrel=1
 pkgdesc="Multi-distro Linux maintenance and installer toolkit"
 arch=('any')
@@ -8,11 +8,34 @@ license=('MIT')
 depends=('python' 'python-pyqt5' 'python-psutil' 'python-matplotlib' 'polkit')
 optdepends=('flatpak: Flatpak app installation support')
 source=()
+sha256sums=()
+
 package() {
-  install -d "$pkgdir/usr/share/tuxpulse"
-  cp -r app "$pkgdir/usr/share/tuxpulse/"
-  cp -r helper "$pkgdir/usr/share/tuxpulse/"
-  install -Dm755 packaging/deb/usr/bin/tuxpulse "$pkgdir/usr/bin/tuxpulse"
-  install -Dm644 packaging/systemd/tuxpulse-helper.service "$pkgdir/usr/lib/systemd/system/tuxpulse-helper.service"
-  install -Dm644 packaging/polkit/com.tuxpulse.policy "$pkgdir/usr/share/polkit-1/actions/com.tuxpulse.policy"
+  local repo_root=""
+
+  if [[ -d "${startdir}/app" && -d "${startdir}/helper" ]]; then
+    repo_root="${startdir}"
+  elif [[ -d "${startdir}/../app" && -d "${startdir}/../helper" ]]; then
+    repo_root="${startdir}/.."
+  elif [[ -d "${startdir}/../../app" && -d "${startdir}/../../helper" ]]; then
+    repo_root="${startdir}/../.."
+  else
+    echo "Could not locate repository root from startdir=${startdir}" >&2
+    return 1
+  fi
+
+  install -d "${pkgdir}/usr/share/tuxpulse"
+  cp -a "${repo_root}/app" "${pkgdir}/usr/share/tuxpulse/"
+  cp -a "${repo_root}/helper" "${pkgdir}/usr/share/tuxpulse/"
+
+  install -Dm755 "${repo_root}/packaging/deb/usr/bin/tuxpulse" \
+    "${pkgdir}/usr/bin/tuxpulse"
+  install -Dm644 "${repo_root}/packaging/systemd/tuxpulse-helper.service" \
+    "${pkgdir}/usr/lib/systemd/system/tuxpulse-helper.service"
+  install -Dm644 "${repo_root}/packaging/polkit/com.tuxpulse.policy" \
+    "${pkgdir}/usr/share/polkit-1/actions/com.tuxpulse.policy"
+  install -Dm644 "${repo_root}/packaging/deb/usr/share/applications/tuxpulse.desktop" \
+    "${pkgdir}/usr/share/applications/tuxpulse.desktop"
+  install -Dm644 "${repo_root}/packaging/deb/usr/share/icons/hicolor/256x256/apps/tuxpulse.png" \
+    "${pkgdir}/usr/share/icons/hicolor/256x256/apps/tuxpulse.png"
 }
